# Generated by Django 4.1.6 on 2023-02-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
    ]
