# Generated by Django 4.1.6 on 2023-02-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_customer_cartitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='customer',
            new_name='user',
        ),
    ]
