# Generated by Django 4.1.6 on 2023-02-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_unit_price_orderitem_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='offer_price',
        ),
    ]
