# Generated by Django 4.1.6 on 2023-02-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_customer_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
